//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditos
    {
        public int Id { get; set; }
        public int Id_fact { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha_lim { get; set; }
        public int Abono { get; set; }
        public int Saldo_r { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
