//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dptos
    {
        public Dptos()
        {
            this.Municipios = new HashSet<Municipios>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Id_pais { get; set; }
    
        public virtual Paises Paises { get; set; }
        public virtual ICollection<Municipios> Municipios { get; set; }
    }
}
