//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Caja = new HashSet<Caja>();
            this.Creditos = new HashSet<Creditos>();
        }
    
        public int Id { get; set; }
        public int Id_persona { get; set; }
        public int Id_tipopago { get; set; }
        public int Id_estado { get; set; }
        public int Id_servplan { get; set; }
        public int Valor_t { get; set; }
        public int Numero_f { get; set; }
        public int Descuento { get; set; }
        public int Interes { get; set; }
        public int Iva { get; set; }
        public int Flete { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<Caja> Caja { get; set; }
        public virtual ICollection<Creditos> Creditos { get; set; }
        public virtual Estados_fact Estados_fact { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Servs_Plns Servs_Plns { get; set; }
        public virtual Tipos_pgs Tipos_pgs { get; set; }
    }
}
