//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd_GYMEntities : DbContext
    {
        public Bd_GYMEntities()
            : base("name=Bd_GYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<C_congeladas> C_congeladas { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Creditos> Creditos { get; set; }
        public virtual DbSet<Dptos> Dptos { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Estados_fact> Estados_fact { get; set; }
        public virtual DbSet<Estados_pers> Estados_pers { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Servs_Plns> Servs_Plns { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_estados> T_estados { get; set; }
        public virtual DbSet<Tipos_pgs> Tipos_pgs { get; set; }
    }
}
