//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sedes
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string NIT { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Id_propietario { get; set; }
        public Nullable<int> Id_empresa { get; set; }
        public Nullable<int> Id_ubicacion { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Municipios Municipios { get; set; }
    }
}
