//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servs_Plns
    {
        public Servs_Plns()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id { get; set; }
        public int Id_servicio { get; set; }
        public int Id_plan { get; set; }
        public int valor { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual Planes Planes { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
