//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dpto
    {
        public Dpto()
        {
            this.Municipios = new HashSet<Municipio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Id_pais { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Municipio> Municipios { get; set; }
    }
}
