//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd_GYMEntities : DbContext
    {
        public Bd_GYMEntities()
            : base("name=Bd_GYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<C_congeladas> C_congeladas { get; set; }
        public DbSet<Caja> Cajas { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Credito> Creditos { get; set; }
        public DbSet<Dpto> Dptos { get; set; }
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<Estados_fact> Estados_fact { get; set; }
        public DbSet<Estados_pers> Estados_pers { get; set; }
        public DbSet<Factura> Facturas { get; set; }
        public DbSet<Municipio> Municipios { get; set; }
        public DbSet<Pais> Paises { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<Plane> Planes { get; set; }
        public DbSet<Sede> Sedes { get; set; }
        public DbSet<Servicio> Servicios { get; set; }
        public DbSet<Servs_Plns> Servs_Plns { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<T_estados> T_estados { get; set; }
        public DbSet<Tipos_pgs> Tipos_pgs { get; set; }
    }
}
