//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public Municipio()
        {
            this.Sedes = new HashSet<Sede>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Id_dpto { get; set; }
    
        public virtual Dpto Dpto { get; set; }
        public virtual ICollection<Sede> Sedes { get; set; }
    }
}
