//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servs_Plns
    {
        public Servs_Plns()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int Id { get; set; }
        public int Id_servicio { get; set; }
        public int Id_plan { get; set; }
        public int valor { get; set; }
    
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
