//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDts
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_estados
    {
        public T_estados()
        {
            this.Estados_pers = new HashSet<Estados_pers>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Estados_pers> Estados_pers { get; set; }
    }
}
